package org.oettel.model.message;

public enum ClientMessageType {
    CLIENT_BROADCAST, CLIENT_BROADCAST_RESPONSE,
    CLIENT_HEARTBEAT, CLIENT_HEARTBEAT_RESPONSE,
    CHAT_MESSAGE, LEADER_ANNOUNCEMENT,
    VECTOR_BROADCAST_RESPONSE,
    NACK, REPLICATION
}
